// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class Biletat
{
    public int? BiletaId { get; set; }

    public int? RezervimiId { get; set; }

    public string NumriBiletës { get; set; }

    public decimal Çmimi { get; set; }

    public DateTime? DataLëshimit { get; set; }

    public virtual Rezervimet Rezervimi { get; set; }
}