// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class ContactMessage
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedAt { get; set; }
}