// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class Pasagjerët
{
    public int? PasagjeriId { get; set; }

    public string Emri { get; set; }

    public string Email { get; set; }

    public string NumriTelefonit { get; set; }

    public DateTime? DataKrijimit { get; set; }

    public virtual ICollection<Rezervimet> Rezervimets { get; set; } = new List<Rezervimet>();
}