// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class Rezervimet
{
    public int? RezervimiId { get; set; }

    public int? PasagjeriId { get; set; }

    public int? OrariId { get; set; }

    public int? NumriVendit { get; set; }

    public string Statusi { get; set; }

    public DateTime? DataKrijimit { get; set; }

    public virtual ICollection<Biletat> Biletats { get; set; } = new List<Biletat>();

    public virtual Oraret Orari { get; set; }

    public virtual Pasagjerët Pasagjeri { get; set; }
}