// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class Rrugët
{
    public int? RrugaId { get; set; }

    public string Origjina { get; set; }

    public string Destinacioni { get; set; }

    public decimal Distanca { get; set; }

    public DateTime? DataKrijimit { get; set; }

    public virtual ICollection<Oraret> Orarets { get; set; } = new List<Oraret>();
}