// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class Shoferët
{
    public int? ShoferiId { get; set; }

    public string Emri { get; set; }

    public string NumriLicencës { get; set; }

    public int? BusId { get; set; }

    public DateTime? DataKrijimit { get; set; }

    public virtual Bus Bus { get; set; }
}