// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class SocialLogin
{
    public int SocialLoginId { get; set; }

    public int UserId { get; set; }

    public string Provider { get; set; }

    public string ProviderKey { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}