// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusMNG.Models;

public partial class UserSession
{
    public Guid SessionId { get; set; }

    public int UserId { get; set; }

    public string TokenHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool? IsValid { get; set; }

    public virtual User User { get; set; }
}